name: Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  client:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn bootstrap

      - name: Build
        run: yarn build:site:client
        env:
          REACT_APP_API_ENDPOINT: ${{ secrets.CLIENT_APP_API_ENDPOINT }}
          REACT_APP_MAPS_API_KEY: ${{ secrets.CLIENT_APP_MAPS_API_KEY }}

      - name: Deploy to test S3
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: test.dudewheresmycovidtest.com
          source_dir: 'sites/client/build'
          destination_dir: ''

#  api:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: upload image to ECR
#        uses: appleboy/docker-ecr-action@master
#        with:
#          access_key: ${{ secrets.AWS_KEY_ID }}
#          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          registry: ${{ secrets.AWS_ECR }}
#          cache_from: ${{ secrets.cache }}
#          repo: api-sample
#          region: ap-northeast-1
#          auto_tag: true
#          daemon_off: false
#          dockerfile: ./ApiDockerfile
#          context: .
